#!/usr/bin/env python3
"""Generate single-header amalgamations (mls_core.h, mls_full.h) from lib/*.

Single source of truth = the files in lib/. The generated headers are plain
concatenations with two known transformations, nothing is duplicated or
hand-edited:

  1. Drop internal `#include "..."` lines (system `<...>` includes stay).
  2. mls_ext.h's trailing `MLS_DEBUG` macro block is emitted between the two
     implementation halves, so mls_base.c/mls_ext.c keep using plain names
     (m_alloc, m_init, ...) while tool/table/extra/... and user code still get
     the line-tracking macros -- identical to the multi-file build.

stb-style usage (define the implementation macro in exactly ONE .c file):

    #define MLS_CORE_IMPLEMENTATION
    #include "mls_core.h"

Run:  python3 generate_amalgam.py
"""

import os

ROOT = os.path.dirname(os.path.abspath(__file__))
LIB = os.path.join(ROOT, "lib")

# Public headers, concatenated in dependency order (base <- ext <- list <- table;
# tool/extra sit on top of the string helpers).
CORE_HEADERS = ["mls_base.h", "mls_ext.h", "list.h", "table.h", "m_tool.h", "m_extra.h"]
FULL_HEADERS = CORE_HEADERS + ["m_http.h", "m_hdf.h", "m_http_server.h", "m_flask.h"]

# Implementation is split around the MLS_DEBUG macro block so debug builds behave
# exactly like the multi-file build:
#   group A (mls_base.c, mls_ext.c, list.c, table.c) must see plain names -- they
#           define m_alloc etc. and only include mls_base.h, not the debug macros.
#   group B (everything else) must see the macros so its allocations are tracked.
GROUP_A = ["mls_internal.h", "mls_base.c", "mls_ext.c", "list.c", "table.c"]
CORE_GROUP_B = ["m_tool.c", "m_extra.c"]
FULL_GROUP_B = CORE_GROUP_B + ["m_http.c", "m_hdf.c", "m_http_server.c", "m_flask.c"]

DEBUG_MACRO_IF = "#if defined(MLS_DEBUG) && !defined(MLS_DEBUG_DISABLE)"
DISABLE_COMMENT = "/* disable macros to override m_alloc, ... */"


def read(name):
    with open(os.path.join(LIB, name), encoding="utf-8") as f:
        return f.read().splitlines()


def strip_internal_includes(lines):
    """Keep system includes, drop project-internal ones (already concatenated)."""
    return [ln for ln in lines if not ln.lstrip().startswith('#include "')]


def strip_disable_define(lines):
    """mls_base.c / mls_ext.c define MLS_DEBUG_DISABLE to protect themselves from
    their own header macros; that would also kill the epilogue macros, so drop it."""
    return [ln for ln in lines
            if ln.strip() != "#define MLS_DEBUG_DISABLE"
            and ln.strip() != DISABLE_COMMENT]


def split_debug_epilogue(lines):
    """mls_ext.h: the trailing MLS_DEBUG macro block is stripped here and re-emitted
    between the two implementation halves (see build())."""
    for i in range(len(lines) - 1, -1, -1):
        if lines[i].strip() == DEBUG_MACRO_IF:
            return lines[:i], lines[i:]
    raise SystemExit("mls_ext.h: debug macro block not found")


def header_banner(title, impl, config=None):
    out = [
        "/* " + title + " — single-header amalgamation of mls.",
        " * Auto-generated by generate_amalgam.py from lib/ — do not edit.",
        " *",
        " * stb-style: define the implementation macro in exactly ONE translation unit:",
        " *     #define " + impl,
        " *     #include \"" + title + "\"",
        " *",
    ]
    if config:
        out += [
            " * Build config: " + config + " (baked in; no -D flags needed).",
            " * Link with " + ("-lpthread " if "multithread" in config else "") + "-lm -ldl.",
        ]
    else:
        out += [
            " * Thread safety: compile with -DMLS_THREAD_SAFE=0 to disable, or it",
            " * auto-enables on Unix/POSIX. Link with -lpthread -lm -ldl.",
        ]
    out += [
        " *",
        " * Include this header first (before <stdio.h> etc.), or define _GNU_SOURCE",
        " * on the command line; the header sets it, but only if no system header",
        " * has been included yet.",
        " */",
        "",
    ]
    return out


def emit_sources(out, names):
    for s in names:
        lines = read(s)
        if s.endswith(".c"):
            lines = strip_disable_define(lines)
        lines = strip_internal_includes(lines)
        out += lines + [""]


def build(title, headers, group_b, impl=None, guard=None, defines=(),
          config=None):
    name = title.replace(".h", "")
    impl = impl or name.upper() + "_IMPLEMENTATION"
    guard = guard or name.upper() + "_H"

    out = header_banner(title, impl, config)
    out += ["#ifndef " + guard, "#define " + guard, ""]
    for dname, dvalue in defines:
        out.append("#undef " + dname)
        if dvalue is not None:
            out.append("#define " + dname + " " + dvalue)
        out.append("")

    epilogue = []
    for h in headers:
        lines = strip_internal_includes(read(h))
        if h == "mls_ext.h":
            lines, epilogue = split_debug_epilogue(lines)
        out += lines + [""]

    out += ["#endif /* " + guard + " */", ""]

    out += ["#ifdef " + impl, ""]
    emit_sources(out, GROUP_A)
    out += ["#endif /* " + impl + " */", ""]

    out += ["/* MLS_DEBUG line-tracking macros (from mls_ext.h); empty in release */", ""]
    out += epilogue + [""]

    out += ["#ifdef " + impl, ""]
    emit_sources(out, group_b)
    out += ["#endif /* " + impl + " */", ""]

    path = os.path.join(ROOT, title)
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(out))
    print("wrote", title, f"({len(out)} lines)")


SMOKE = r'''
#define IMPLMACRO
#include "HEADER"
#include <stdio.h>
int main(void) {
    m_init();
    int h = m_alloc(4, sizeof(int), MFREE);
    for (int i = 0; i < 3; i++) m_put(h, &i);
    printf("%d\n", INT(h, 1));
    int s = s_cstrdup("mls");
    printf("%s\n", m_str(s));
    const char *cols[] = {"id", "name"};
    int l = m_wrapstrhandles(cols, 2);
    int sep = s_dup(",");
    int j = s_implode_q(0, l, sep, '\'');
    printf("%s\n", m_str(j));
    m_free(j); m_free(l); m_free(sep);
    m_free(s); m_free(h);
    m_destruct();
    return 0;
}
'''


# Standalone core presets: each is a full amalgamation with the build config
# baked in at the top, so a user can copy one file and compile without -D flags.
# (filename, debug, multithread)
CORE_PRESETS = [
    ("mls_core.h", False, False),
    ("mls_coremt.h", False, True),
    ("mls_cored.h", True, False),
    ("mls_coredmt.h", True, True),
]

CHECK_HEADERS = [
    ("mls_core.h", "MLS_CORE_IMPLEMENTATION"),
    ("mls_coremt.h", "MLS_CORE_IMPLEMENTATION"),
    ("mls_cored.h", "MLS_CORE_IMPLEMENTATION"),
    ("mls_coredmt.h", "MLS_CORE_IMPLEMENTATION"),
    ("mls_full.h", "MLS_FULL_IMPLEMENTATION"),
]


def build_presets():
    for title, debug, mt in CORE_PRESETS:
        config = "%s, %s" % ("debug" if debug else "release",
                             "multithread" if mt else "single-threaded")
        defines = [("MLS_DEBUG", "1" if debug else None),
                   ("MLS_THREAD_SAFE", "1" if mt else "0")]
        build(title, CORE_HEADERS, CORE_GROUP_B,
              impl="MLS_CORE_IMPLEMENTATION",
              guard=title.replace(".", "_").upper(),
              defines=defines, config=config)


def check():
    import subprocess
    import tempfile

    cc = os.environ.get("CC", "cc")
    tmp = tempfile.mkdtemp(prefix="mls_amalgam_")
    try:
        for header, impl in CHECK_HEADERS:
            src = os.path.join(tmp, "t.c")
            with open(src, "w") as f:
                f.write(SMOKE.replace("HEADER", header).replace(
                    "IMPLMACRO", impl))
            exe = os.path.join(tmp, "t")
            subprocess.run([cc, "-std=c11", "-I", ROOT, src, "-o", exe,
                            "-lpthread", "-lm", "-ldl"], check=True)
            out = subprocess.run([exe], check=True, capture_output=True, text=True)
            assert out.stdout == "1\nmls\n'id','name'\n", (header, out.stdout)
        print("amalgam check OK")
    finally:
        import shutil
        shutil.rmtree(tmp, ignore_errors=True)


if __name__ == "__main__":
    # Core presets are full standalone amalgamations with the config baked in;
    # the impl macro is MLS_CORE_IMPLEMENTATION for all of them.
    build_presets()
    build("mls_full.h", FULL_HEADERS, FULL_GROUP_B)
    if "--check" in __import__("sys").argv:
        check()
